### ISSUE TITLE
SINDc : SINDy with control

### ISSUE THREAD

**Issue by finmod** [SciML/DataDrivenDiffEq.jl#109]
@ChrisRackauckas It should be possible to readily extend the current SINDy to predictive control as in: 
https://royalsocietypublishing.org/doi/pdf/10.1098/rspa.2018.0335 including writing out the discovered optimal control solution with ModelingToolkit (OptimalControlSystem).

**Comment by ChrisRackauckas** [comment]
That sounds like a great thing to add!

**Comment by finmod** [comment]
The whole of chapter 10 in Data-Driven Science and Engineering: Machine Learning, Dynamical Systems, and Control, Steven L. Brunton, J. Nathan Kutz constitutes a roadmap of gradual improvements to DataDrivenDiffEq (DMDc, reinforcement learning).

**Comment by AlCap23** [comment]
Could / Can be done pretty easily right now. The only thing holding me back is deciding on the API.

In general, we already can do SINDyC, since we already allow the states and measurements to differ. This is the needed general form ` DX = f(X, U, p, t)`. But the transformation into an `ODESystem` depends somehow on [this](https://github.com/SciML/ModelingToolkit.jl/issues/362) issue in MTK, I think :)

[DMDc](https://datadriven.sciml.ai/dev/koopman/dmdc/) is already implemented, but could be easily extended to EDMDc ( or similar ).

The book is a really good companion, which captures most of the related stuff from the papers in a condensed from.

**Comment by finmod** [comment]
KRONIC should be a natural extension of the many examples already available in DataDrivenDiffEq. This group of researchers is really on to something original.
