### ISSUE TITLE
`SINDy(::AbstractODESolution, ...)` and adding Sol dispatch to library functions

### ISSUE THREAD

**Issue by anandijain** [SciML/DataDrivenDiffEq.jl#206]
It'd be nice to extend a lot of these methods directly to AbstractODESolution to make the integration even tighter with SciML. 
It seems tedious to need to Array(sol). 

Potentially relevant #172 

```julia
X = Array(solution)
DX = similar(X)
for (i, xi) in enumerate(eachcol(X))
    DX[:,i] = lorenz(xi, [], 0.0)
end
```
It could just make DX for you.

**Comment by AlCap23** [comment]
On the current main branch, I am including the DataDrivenProblem type, which could handle this. For control signals this is already been done, so you can pass in a function u,p,t->control. Additionally, this also includes numerical derivative calculation. 

I don't know if a function makes sense, because the only usecase I can think of is to evaluate trained surrogates like in the UDE case. But maybe this can be useful for model reduction. I will keep this in mind 🙃

**Comment by anandijain** [comment]
yes MOR is the use case I had in mind 🙂. thanks!

**Comment by AlCap23** [comment]
Since #222 included
