### ISSUE TITLE
SINDy error when derivative values are small

### ISSUE THREAD

**Issue by bkuwahara** [SciML/DataDrivenDiffEq.jl#220]
I've been getting this error `ArgumentError: range must be non-empty` when attempting to use SINDy. It only seems to happen when the derivative values are small compared to the state values. For a contrived example, 
```
@variables u
b = [polynomial_basis([u], 3); sin(u)]
basis = Basis(b, [u])
X = rand(1, 10)
Y = 1e-2.*(2*X .+1)
Ψ=SINDy(X, Y, basis)
# Gives the error
```
versus
```
X = rand(1, 10)
Y = 1e-1*(2*X .+1)
Ψ=SINDy(X, Y, basis)
print_equations(Ψ)

Independent variable: t
Equations
φ₁ = p₁ + p₂*u
```
It also seems to break when all values are 0:
```
X = zeros(1,10)
Y = zeros(1,10)
Ψ = SINDy(X, Y, basis)
print_equations(Ψ)

Independent variable: t
Equations
φ₁ = p₁ + p₂*u + p₃*(u^2) + p₄*(u^3) + p₅*sin(u)
```
which doesn't make much sense to me. 

This is all on v0.5.7. Any idea what causes this phenomenon? Is there a way to prevent it if my dynamical system inherently has small derivative values?

**Comment by AlCap23** [comment]
This happens when all terms in the coefficients are zero which depends strongly on the threshold of the optimizer.

I think the derivative values do not play such an important role opposed to the candidate library. You might use a varying threshold:

```julia
@variables u
b = [polynomial_basis([u], 3); sin(u)]
basis = Basis(b, [u])
X = rand(1, 10)
Y = 1e-2.*(2*X .+1)
lamdas = exp10.(-4:0.1:0)
Ψ=SINDy(X, Y, basis, lambdas)
# Gives the error
```
Which might help. The standard threshold is 1e-1, just using your example as input, all values of the regression are < 3e-2, so they get all pushed down to zero.

But this should and will be handled in 0.6.x

**Comment by bkuwahara** [comment]
Ah that makes sense. Using the varying lambdas threshold works. Thank you very much!
