### ISSUE TITLE
Some clarification on the documentation, what is U?

### ISSUE THREAD

**Issue by gzagatti** [SciML/DataDrivenDiffEq.jl#235]
First of all thanks for putting the library together!

I am seeking some clarification on the documentation for the definition of the data problem.

In the [example of the non-linear pendulum](https://datadriven.sciml.ai/dev/quickstart/#Nonlinear-Systems-Sparse-Identification-of-Nonlinear-Dynamics)  a function is passed as an argument to `U` in the definition of the `ContinuousDataDrivenProblem`:

```julia
prob = ContinuousDataDrivenProblem(X, ts, GaussianKernel(), U = (u,p,t)->[exp(-((t-5.0)/5.0)^2)], p = ones(2))
```

The [API documentation](https://datadriven.sciml.ai/dev/prob_and_solve/#DataDrivenDiffEq.DataDrivenProblem) states that `U` is an input measurement. However, it is not entirely clear to me what is the role of `U`. 

Further down in the tutorial, the `Basis` is initialized with `controls=c`. Is this somehow related with `U`? If not, what is the purpose of `controls` as well?

My understanding is that `SLTSQ` only needs a method for estimating the derivative which is provided by `GaussianKernel()`.

Please let me know, if I should rather post this on Discourse. It was not clear if it might be an issue with the documentation.

**Comment by AlCap23** [comment]
Ah, good point. 

`U` is indeed the input signal to the forced, nonlinear system. We assume we measure this directly / know the generating function.  So this is part of the problem definition since it's data. It does not influence the generation of the derivatives, but should be included in the estimation problem.

We also now that this input plays a role in the dynamics, but strictly speaking not part of the state space. So we extend this to be X times U. To distinguish, we need to separate those spaces / variables further along, hence the extra `controls = ...` part. 

See the [paper on SINDyc](https://www.sciencedirect.com/science/article/pii/S2405896316318298)

**Comment by gzagatti** [comment]
Thanks for sharing the paper, as I was not aware of it! Quickly scanning I can see that I will find the more detailed answer in there. 

Once the documentation matures, might be a good idea to include a pointer to it in there.
