### ISSUE TITLE
SInDy_Examples2 and ISInDy_Examples not working

### ISSUE THREAD

**Issue by gabrevaya** [SciML/DataDrivenDiffEq.jl#74]
At least `SInDy_Examples2.jl` and `ISInDy_Examples.jl` are not finding the correct equations any more. I'm not sure why.

In `SInDy_Examples2.jl` the Savitzy-Golay filter still seems to still work well (`isapprox(DX_sg, DX, rtol=1e-2) # true` ) but `SInDy` is not getting the right eqs, not even with SR3 and varying its sparsity threshold.

In the case of ISInDy, it was even more unexpected since a test almost identical to that example is included in `runtest.jl` and it is passing. I noticed that when using `u0 =  randn(3)*5.0` (as in the example), instead of the fixed `u0 = [2.37; 1.58; -3.10]`, the test also fails.

**Comment by AlCap23** [comment]
I found the "error" in the `SInDy_Examples2.jl`. Since we now normalize the candidate functions as a standard now, this failed ( due to the amplitudes of the polynomials ). If you use 

```julia
# Get the reduced basis via the sparse regression
opt = STRRidge(0.1)
Ψ = SInDy(X_cropped, DX_sg, basis, maxiter = 100, opt = opt, denoise = false, normalize = false)
print(Ψ)
```

everything should work as expected.

As for the `ISInDy` examples, you should have a look at the data first. I will remove the random initial conditions, since they tend to produce very steady state like motion sometimes, which is in fact useless for the estimation. Do you experience other issues ?

I'll fix the examples within this week.

**Comment by gabrevaya** [comment]
Great! Thanks @AlCap23!

I can fix these examples too, don't worry.
I haven't found other issues yet but I didn't finish catching up with all the amazing features that you added in the time I was absent :) I'll let you know if I find more.

I'm willing to come back to contribute to this project, so I'll talk to you via slack to organize what is best for me to work in.
